// Approximate FIFA Men's World Ranking positions for the 48 teams at WC 2026.
// Used as a prior strength signal (especially for teams that haven't played
// a match in this tournament yet). Snapshot is approximate, not live data.
export const FIFA_RANKINGS: Record<string, number> = {
  Spain: 1,
  Argentina: 2,
  France: 3,
  England: 4,
  Brazil: 5,
  Portugal: 6,
  Netherlands: 7,
  Belgium: 8,
  Germany: 9,
  Croatia: 10,
  Morocco: 11,
  Colombia: 12,
  Uruguay: 13,
  Japan: 14,
  "United States": 15,
  Mexico: 16,
  Switzerland: 17,
  Senegal: 18,
  Iran: 19,
  Ecuador: 20,
  Austria: 21,
  Australia: 22,
  "South Korea": 23,
  Tunisia: 24,
  Sweden: 25,
  Egypt: 26,
  Canada: 27,
  Norway: 28,
  Panama: 29,
  "Ivory Coast": 30,
  Ghana: 31,
  Algeria: 32,
  Paraguay: 33,
  Scotland: 34,
  Qatar: 35,
  "Saudi Arabia": 36,
  Turkey: 37,
  Iraq: 38,
  Jordan: 39,
  Uzbekistan: 40,
  "Bosnia-Herzegovina": 41,
  "South Africa": 42,
  "New Zealand": 43,
  Czechia: 44,
  "Congo DR": 45,
  "Cape Verde Islands": 46,
  Curaçao: 47,
  Haiti: 48,
};

export function getFifaRanking(teamName: string): number | null {
  return FIFA_RANKINGS[teamName] ?? null;
}
