import { Group, Match, Team } from "./types";

// Placeholder data used until FOOTBALL_DATA_API_KEY is configured.
// Shapes mirror the football-data.org v4 API so swapping to live data is seamless.

const teams = {
  mexico: { id: 1, name: "Mexico", shortName: "MEX", flag: "🇲🇽" },
  brazil: { id: 2, name: "Brazil", shortName: "BRA", flag: "🇧🇷" },
  nigeria: { id: 3, name: "Nigeria", shortName: "NGA", flag: "🇳🇬" },
  norway: { id: 4, name: "Norway", shortName: "NOR", flag: "🇳🇴" },
  canada: { id: 5, name: "Canada", shortName: "CAN", flag: "🇨🇦" },
  spain: { id: 6, name: "Spain", shortName: "ESP", flag: "🇪🇸" },
  egypt: { id: 7, name: "Egypt", shortName: "EGY", flag: "🇪🇬" },
  australia: { id: 8, name: "Australia", shortName: "AUS", flag: "🇦🇺" },
  usa: { id: 9, name: "United States", shortName: "USA", flag: "🇺🇸" },
  germany: { id: 10, name: "Germany", shortName: "GER", flag: "🇩🇪" },
  colombia: { id: 11, name: "Colombia", shortName: "COL", flag: "🇨🇴" },
  japan: { id: 12, name: "Japan", shortName: "JPN", flag: "🇯🇵" },
  argentina: { id: 13, name: "Argentina", shortName: "ARG", flag: "🇦🇷" },
  portugal: { id: 14, name: "Portugal", shortName: "POR", flag: "🇵🇹" },
  senegal: { id: 15, name: "Senegal", shortName: "SEN", flag: "🇸🇳" },
  southKorea: { id: 16, name: "South Korea", shortName: "KOR", flag: "🇰🇷" },
} satisfies Record<string, Team>;

export const mockMatches: Match[] = [
  // Group A
  {
    id: 101,
    utcDate: "2026-06-11T18:00:00Z",
    status: "FINISHED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group A",
    homeTeam: teams.mexico,
    awayTeam: teams.brazil,
    homeScore: 1,
    awayScore: 2,
  },
  {
    id: 102,
    utcDate: "2026-06-11T21:00:00Z",
    status: "FINISHED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group A",
    homeTeam: teams.nigeria,
    awayTeam: teams.norway,
    homeScore: 0,
    awayScore: 0,
  },
  {
    id: 103,
    utcDate: "2026-06-17T18:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group A",
    homeTeam: teams.mexico,
    awayTeam: teams.nigeria,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 104,
    utcDate: "2026-06-17T21:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group A",
    homeTeam: teams.brazil,
    awayTeam: teams.norway,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 105,
    utcDate: "2026-06-21T18:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group A",
    homeTeam: teams.mexico,
    awayTeam: teams.norway,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 106,
    utcDate: "2026-06-21T18:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group A",
    homeTeam: teams.brazil,
    awayTeam: teams.nigeria,
    homeScore: null,
    awayScore: null,
  },

  // Group B
  {
    id: 201,
    utcDate: "2026-06-11T15:00:00Z",
    status: "FINISHED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group B",
    homeTeam: teams.canada,
    awayTeam: teams.spain,
    homeScore: 0,
    awayScore: 3,
  },
  {
    id: 202,
    utcDate: "2026-06-12T18:00:00Z",
    status: "FINISHED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group B",
    homeTeam: teams.egypt,
    awayTeam: teams.australia,
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: 203,
    utcDate: "2026-06-18T15:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group B",
    homeTeam: teams.canada,
    awayTeam: teams.egypt,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 204,
    utcDate: "2026-06-18T18:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group B",
    homeTeam: teams.spain,
    awayTeam: teams.australia,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 205,
    utcDate: "2026-06-22T15:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group B",
    homeTeam: teams.canada,
    awayTeam: teams.australia,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 206,
    utcDate: "2026-06-22T15:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group B",
    homeTeam: teams.spain,
    awayTeam: teams.egypt,
    homeScore: null,
    awayScore: null,
  },

  // Group C
  {
    id: 301,
    utcDate: "2026-06-12T15:00:00Z",
    status: "FINISHED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group C",
    homeTeam: teams.usa,
    awayTeam: teams.colombia,
    homeScore: 2,
    awayScore: 2,
  },
  {
    id: 302,
    utcDate: "2026-06-12T21:00:00Z",
    status: "FINISHED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group C",
    homeTeam: teams.germany,
    awayTeam: teams.japan,
    homeScore: 4,
    awayScore: 1,
  },
  {
    id: 303,
    utcDate: "2026-06-19T15:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group C",
    homeTeam: teams.usa,
    awayTeam: teams.germany,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 304,
    utcDate: "2026-06-19T18:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group C",
    homeTeam: teams.colombia,
    awayTeam: teams.japan,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 305,
    utcDate: "2026-06-23T15:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group C",
    homeTeam: teams.usa,
    awayTeam: teams.japan,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 306,
    utcDate: "2026-06-23T15:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group C",
    homeTeam: teams.germany,
    awayTeam: teams.colombia,
    homeScore: null,
    awayScore: null,
  },

  // Group D - matchday 1 in progress today
  {
    id: 401,
    utcDate: "2026-06-13T16:00:00Z",
    status: "IN_PLAY",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group D",
    homeTeam: teams.argentina,
    awayTeam: teams.senegal,
    homeScore: 1,
    awayScore: 0,
  },
  {
    id: 402,
    utcDate: "2026-06-13T19:00:00Z",
    status: "SCHEDULED",
    matchday: 1,
    stage: "GROUP_STAGE",
    group: "Group D",
    homeTeam: teams.portugal,
    awayTeam: teams.southKorea,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 403,
    utcDate: "2026-06-19T21:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group D",
    homeTeam: teams.argentina,
    awayTeam: teams.portugal,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 404,
    utcDate: "2026-06-20T15:00:00Z",
    status: "SCHEDULED",
    matchday: 2,
    stage: "GROUP_STAGE",
    group: "Group D",
    homeTeam: teams.senegal,
    awayTeam: teams.southKorea,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 405,
    utcDate: "2026-06-24T15:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group D",
    homeTeam: teams.argentina,
    awayTeam: teams.southKorea,
    homeScore: null,
    awayScore: null,
  },
  {
    id: 406,
    utcDate: "2026-06-24T15:00:00Z",
    status: "SCHEDULED",
    matchday: 3,
    stage: "GROUP_STAGE",
    group: "Group D",
    homeTeam: teams.portugal,
    awayTeam: teams.senegal,
    homeScore: null,
    awayScore: null,
  },
];

export const mockGroups: Group[] = [
  {
    name: "Group A",
    standings: [
      { position: 1, team: teams.brazil, playedGames: 1, won: 1, draw: 0, lost: 0, points: 3, goalsFor: 2, goalsAgainst: 1, goalDifference: 1 },
      { position: 2, team: teams.nigeria, playedGames: 1, won: 0, draw: 1, lost: 0, points: 1, goalsFor: 0, goalsAgainst: 0, goalDifference: 0 },
      { position: 3, team: teams.norway, playedGames: 1, won: 0, draw: 1, lost: 0, points: 1, goalsFor: 0, goalsAgainst: 0, goalDifference: 0 },
      { position: 4, team: teams.mexico, playedGames: 1, won: 0, draw: 0, lost: 1, points: 0, goalsFor: 1, goalsAgainst: 2, goalDifference: -1 },
    ],
  },
  {
    name: "Group B",
    standings: [
      { position: 1, team: teams.spain, playedGames: 1, won: 1, draw: 0, lost: 0, points: 3, goalsFor: 3, goalsAgainst: 0, goalDifference: 3 },
      { position: 2, team: teams.egypt, playedGames: 1, won: 0, draw: 1, lost: 0, points: 1, goalsFor: 1, goalsAgainst: 1, goalDifference: 0 },
      { position: 3, team: teams.australia, playedGames: 1, won: 0, draw: 1, lost: 0, points: 1, goalsFor: 1, goalsAgainst: 1, goalDifference: 0 },
      { position: 4, team: teams.canada, playedGames: 1, won: 0, draw: 0, lost: 1, points: 0, goalsFor: 0, goalsAgainst: 3, goalDifference: -3 },
    ],
  },
  {
    name: "Group C",
    standings: [
      { position: 1, team: teams.germany, playedGames: 1, won: 1, draw: 0, lost: 0, points: 3, goalsFor: 4, goalsAgainst: 1, goalDifference: 3 },
      { position: 2, team: teams.usa, playedGames: 1, won: 0, draw: 1, lost: 0, points: 1, goalsFor: 2, goalsAgainst: 2, goalDifference: 0 },
      { position: 3, team: teams.colombia, playedGames: 1, won: 0, draw: 1, lost: 0, points: 1, goalsFor: 2, goalsAgainst: 2, goalDifference: 0 },
      { position: 4, team: teams.japan, playedGames: 1, won: 0, draw: 0, lost: 1, points: 0, goalsFor: 1, goalsAgainst: 4, goalDifference: -3 },
    ],
  },
  {
    name: "Group D",
    standings: [
      { position: 1, team: teams.argentina, playedGames: 0, won: 0, draw: 0, lost: 0, points: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0 },
      { position: 2, team: teams.portugal, playedGames: 0, won: 0, draw: 0, lost: 0, points: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0 },
      { position: 3, team: teams.senegal, playedGames: 0, won: 0, draw: 0, lost: 0, points: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0 },
      { position: 4, team: teams.southKorea, playedGames: 0, won: 0, draw: 0, lost: 0, points: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0 },
    ],
  },
];
